### ISSUE TITLE
Bring the Overview / Board filters to the Calendar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1635] opened 2024-05-16 19:26 UTC
Can we bring the same filters from the Overview / Board screen to the Calendar?

![Screenshot 2024-05-16 at 3 24 46 PM](https://github.com/publishpress/PublishPress-Planner/assets/3868028/741c57cf-4123-4743-ae2f-a0b59e6e45f7)

**Comment by olatechpro** [comment] 2024-07-14 07:35
@stevejburge Content Calendar own is going to be difficult due to the calendar been reactjs and also, it has it own modal, it's possible though but will take time as it's impossible to copy Content Board code(php) but instead, will need to implement it for react separately in reactjs.

**Comment by olatechpro** [comment] 2024-07-14 07:45
Duplicate of https://github.com/publishpress/PublishPress-Planner/issues/1603

**Closed by olatechpro** 2024-07-14 07:45 UTC
